### PR TITLE
UI Rewrite

### PR DESCRIPTION
**Pull request by lishaduck**
## Description

This PR redoes as much of the UI as I can, in modular, step-by-step atomic commits.

---

## Type of Change

- ✨ New feature

## Checklist

```[tasklist]
### Checklist
- [x] Read the Contributing Guidelines.
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Fill out this template.
- [ ] Log your hours.
- [x] Check that commits follow the Angular commit convention, more or less.
- [ ] Ideally, include relevant tests that fail without this PR but pass with it (if applicable).
```

## Tested on

- macOS 14

### CODE REVIEW

**Comment by lishaduck** [comment]
@MattsAttack, do you a font preference? Arial is boring, and we should load a font ourselves anyway for consistency.
Tailwind recommends [Inter](https://rsms.me/inter/), but we don't want to have a basic Tailwind site, do we?
I'm open to anything that's not hideous.

**Comment by MattsAttack** [comment]
I use montersont(spelling may be off) on Canva and it looks nice. Your call
though as I’m not a font guy

**Comment by lishaduck** [comment]
@MattsAttack, [Montserrat](https://fonts.google.com/specimen/Montserrat)? I love that font (usually, depends on my mood)!

**Comment by lishaduck** [comment]
> I use montersont(spelling may be off) on Canva and it looks nice. Your call though as I’m not a font guy

I've tried to set this up, but it's slow so it decimates our LCP and CLS. It's actually enough to bother me, so I'm calling it off. Anyway, the tailwind defaults work well enough, the fonts'll be on iphones (at least, they should be), so shouldn't be to inconsistent. We'll be fine.
Also, the default fonts look nice anyway. Montserrat looks kinda tacky, I'll admit.

**Comment by lishaduck** [comment]
We can skip the chatbox change if needed. I've messed with it for quite a bit, and don't know how to fix it. Otherwise, this is ready to go!

**Pull request merged**
